# docker-compose.yml

version: '3'

services:
  vuejs:
    container_name: vuejs
    build: ./frontend
    image: frontend/vuejs
    restart: always
    ports:
      - '80:80'
    depends_on:
      - django

  django:
    container_name: django
    build: ./backend
    image: backend/django
    restart: always
    ports:
      - '8000:8000'
